### ISSUE TITLE
Failed to extract an archive

### ISSUE THREAD

**Issue by spokko** [windowschefcookbooks/seven_zip#10]
7zip fails when trying to extract any type of archive with following error:
NoMethodError
-------------
No resource or method named `cached_file' for `LWRP provider seven_zip_archive from cookbook seven_zip ""'
Cookbook Trace:
---------------
c:/chef/cache/cookbooks/seven_zip/providers/archive.rb:36:in `block (2 levels) in class_from_file'
c:/chef/cache/cookbooks/seven_zip/providers/archive.rb:34:in `block in class_from_file'

*** Chef 12.19.36 ***

**Comment by jugatsu** [comment]
Duplicate https://github.com/windowschefcookbooks/seven_zip/issues/7
You should use `windows` cookbook version >=3.0.4
